#!/bin/bash
# ---------------------------------------------------------------------------------------------
# MIT License
#
# Copyright (c) 2020, Solace Corporation, Ricardo Gomez-Ulmke (ricardo.gomez-ulmke@solace.com)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# ---------------------------------------------------------------------------------------------

-
  name: "Test module: solace_get_client_usernames"
  hosts: "{{ brokers }}"
  gather_facts: no
  module_defaults:
    solace_client_username:
      host: "{{ sempv2_host }}"
      port: "{{ sempv2_port }}"
      secure_connection: "{{ sempv2_is_secure_connection }}"
      username: "{{ sempv2_username }}"
      password: "{{ sempv2_password }}"
      timeout: "{{ sempv2_timeout }}"
      msg_vpn: "{{ vpn }}"
    solace_get_client_usernames:
      host: "{{ sempv2_host }}"
      port: "{{ sempv2_port }}"
      secure_connection: "{{ sempv2_is_secure_connection }}"
      username: "{{ sempv2_username }}"
      password: "{{ sempv2_password }}"
      timeout: "{{ sempv2_timeout }}"
      msg_vpn: "{{ vpn }}"

  tasks:

    - name: Get pre-existing client usernames
      solace_get_client_usernames:
        query_params:
          where:
            - "clientUsername==ansible-solace__test*"
          select:
            - "clientUsername"
      register: pre_existing_list

    - name: Print pre-existing list
      debug:
        msg: "{{ pre_existing_list.result_list }}"

    - name: Print count of pre-existing list
      debug:
        msg: "{{ pre_existing_list.result_list_count }}"

    - name: Remove all found client usernames
      solace_client_username:
        name: "{{ item.clientUsername }}"
        state: absent
      register: result
      loop: "{{ pre_existing_list.result_list }}"

    - include_vars:
        file: "./lib/vars.json"
        name: target_list

    - name: Adding / updating client usernames
      solace_client_username:
        name: "{{ item.name }}"
        state: present
      loop: "{{ target_list.clientUsernames }}"

    - name: Get new client usernames
      solace_get_client_usernames:
        query_params:
          where:
            - "clientUsername==ansible-solace__test*"
          select:
            - "clientUsername"
      register: new_list_result

    - name: Print new client username list
      debug:
        msg: "{{ new_list_result.result_list }}"

    - name: Print count of new client username list
      debug:
        msg: "{{ new_list_result.result_list_count }}"

    - name: Fail when new client username list count != 4
      fail:
        msg: "new client username list count != 4"
      when: new_list_result.result_list_count != 4

    - name: Remove all client usernames again
      solace_client_username:
        name: "{{ item.name }}"
        state: absent
      register: result
      loop: "{{ target_list.clientUsernames }}"


###
# The End.
