- name: Playbook to add a DMR Cluster named 'foo'
  hosts: localhost
  tasks:
  - name: Remove 'foo' DMR Cluster
    solace_dmr_cluster:
      name: foo
      state: absent
  - name: Add 'foo' DMR Cluster
    solace_dmr_cluster:
      name: foo
      state: present
      settings:
        tlsServerCertMaxChainDepth: 6
        authenticationBasicPassword: secret_password
    register: testout

  - name: dump output
    debug:
      msg: '{{ testout }}'

  - name: Remove 'remoteNode' DMR Link
    solace_dmr_cluster_link:
      name: remoteNode
      dmr: foo
      state: absent

  - name: Add 'remoteNode' DMR Link
    solace_dmr_cluster_link:
      name: remoteNode
      dmr: foo
      state: present
      settings:
        enabled: false
        authenticationBasicPassword: secret_password
        span: internal
        initiator: local

  - name: Remove 'remoteNode' DMR Link Remote address
    solace_dmr_cluster_link_remote_address:
      name: 192.168.0.34
      remote_node_name: remoteNode
      dmr: foo
      state: absent

  - name: Add 'remoteNode' DMR Link Remote address
    solace_dmr_cluster_link_remote_address:
      name: 192.168.0.34
      remote_node_name: remoteNode
      dmr: foo
      state: present

  - name: Remove 'remoteNode' DMR Link Trusted CN
    solace_dmr_cluster_link_trusted_cn:
      name: "*.messaging.solace.cloud"
      remote_node_name: remoteNode
      dmr: foo
      state: absent

  - name: Add 'remoteNode' DMR Link Trusted CN
    solace_dmr_cluster_link_trusted_cn:
      name: "*.messaging.solace.cloud"
      remote_node_name: remoteNode
      dmr: foo
      state: present


  - name: Enable 'remoteNode' DMR Link
    solace_dmr_cluster_link:
      name: remoteNode
      dmr: foo
      settings:
        enabled: true
        egressFlowWindowSize: 127
